### ISSUE TITLE
hardcoded schema location

### ISSUE THREAD

**Issue by daniel-baumann** [gfxmonk/gnome-shell-impatience#7]
Hi Tim,

the impatience extensions hardcodes to lookup for the schema from the local schema subdirectory. This works fine if the extension is installed in the users home.

However, when installing the extension system-wide in /usr/share/gnome-shell/extensions, the schemas are to be put into /usr/share/glib-2.0/schemas. It would be nice if you could do lookup to find the schema, regardless if the extension is installed for a particular user or system wide.

It seems the usual way to do this is to use something like the getSettings(schema) function here:
https://sources.debian.net/src/gnome-shell-extensions/3.14.2-1/lib/convenience.js/#L65

Regards,
Daniel

**Comment by gfxmonk** [comment]
Sure thing. I've just added 4903eaa303dc8ea2aa52dc9bacef6f99586765fa, which ought to fix this, but I don't have a global install to test on. Can you test this commit (the current `master) and let me know if it works for you?

**Comment by daniel-baumann** [comment]
great, thanks. will do tomorrow and let you know.

**Comment by daniel-baumann** [comment]
sorry for the late reply. works perfectly, thank you very much.
